@startuml
'https://plantuml.com/class-diagram
'
'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}

'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}
namespace UnityEngine.Rendering{
    RenderPipeline <|-- UniversalRenderPipeline

    abstract class RenderPipeline{
        {abstract} void Render()
        void ProcessRenderRequests()
        {static}void BeginFrameRendering()
        {static}void BeginCameraRendering()
        {static}void EndFrameRendering()
        {static}void EndCameraRendering()
        void InternalRender()
        void InternalRenderWithRequests()
        + bool disposed
        void Dispose()
        virtual void Dispose(bool disposing)     
    }
    class UniversalRenderPipeline {
    }
}

@enduml